def simples(baralho):
    print("\nCarta 1 - Passado:\n\t" + baralho.sorteia_carta())
    print("\nCarta 2 - Presente:\n\t" + baralho.sorteia_carta())
    print("\nCarta 3 - Futuro:\n\t" + baralho.sorteia_carta())
    print("")

def celta(baralho):
    print("\nCarta 1 - Situação atual:\n\t" + baralho.sorteia_carta())
    print("\nCarta 2 - O que está atravessado:\n\t" + baralho.sorteia_carta())
    print("\nCarta 3 - Situação externa:\n\t" + baralho.sorteia_carta())
    print("\nCarta 4 - Situação interna:\n\t" + baralho.sorteia_carta())
    print("\nCarta 5 - O que precisa ficar no passado:\n\t" + baralho.sorteia_carta())
    print("\nCarta 6 - Conselho para o futuro:\n\t" + baralho.sorteia_carta())
    print("\nCarta 7 - Sua atitude frente a situação:\n\t" + baralho.sorteia_carta())
    print("\nCarta 8 - Imagem externa sobre você:\n\t" + baralho.sorteia_carta())
    print("\nCarta 9 - Esperanças e temores:\n\t" + baralho.sorteia_carta())
    print("\nCarta 10 - Consequência natural:\n\t" + baralho.sorteia_carta())
    print("")

def templo_de_mercurio(baralho):
    print("\nCarta 1 - Recado do mundo:\n\t" + baralho.sorteia_carta())
    print("\nCarta 2 - Recado dos céus:\n\t" + baralho.sorteia_carta())
    print("\nCarta 3 - Recado do submundo:\n\t" + baralho.sorteia_carta())
    print("\nCarta 4 - Caminho A:\n\t" + baralho.sorteia_carta())
    print("\nCarta 5 - Caminho B:\n\t" + baralho.sorteia_carta())
    print("\nCarta 6 - Resultado do caminho A:\n\t" + baralho.sorteia_carta())
    print("\nCarta 7 - Resultado do caminho B:\n\t" + baralho.sorteia_carta())
    print("\nCarta 8 - Conselho final do Psicopompo:\n\t" + baralho.sorteia_carta())
    print("")

def templo_de_afrodite(baralho):
    print("\nPlano mental:")
    print("\nCarta 1 - Você em relação a pessoa:\n\t" + baralho.sorteia_carta())
    print("\nCarta 2 - A pessoa em relação a você:\n\t" + baralho.sorteia_carta())
    print("\nPlano afetivo:")
    print("\nCarta 3 - Você em relação a pessoa:\n\t" + baralho.sorteia_carta())
    print("\nCarta 4 - A pessoa em relação a você:\n\t" + baralho.sorteia_carta())
    print("\nPlano sexual:")
    print("\nCarta 5 - Você em relação a pessoa:\n\t" + baralho.sorteia_carta())
    print("\nCarta 6 - A pessoa em relação a você:\n\t" + baralho.sorteia_carta())
    print("\nCarta 7 - O resultado final esperado:\n\t" + baralho.sorteia_carta())
    print("")

def templo_de_marte(baralho):
    print("\nCarta 1 - Seus pontos fortes:\n\t" + baralho.sorteia_carta())
    print("\nCarta 2 - Seus pontos fracos:\n\t" + baralho.sorteia_carta())
    print("\nCarta 3 - Pontos fortes do adversário:\n\t" + baralho.sorteia_carta())
    print("\nCarta 4 - Pontos fracos do adversário:\n\t" + baralho.sorteia_carta())
    print("\nCarta 5 - Conselho final:\n\t" + baralho.sorteia_carta())
    print("")